Add workflow to trigger release (#15)
Signed-off-by: LE SAULNIER Kevin <kevin.lesaulnier@rte-france.com>

diff --git a/.github/workflows/dispatch-release.yml b/.github/workflows/dispatch-release.yml
--- a/.github/workflows/dispatch-release.yml
+++ b/.github/workflows/dispatch-release.yml
@@ -1,11 +1,85 @@
-name: Prepare release
+name: Dispatch release
 
 on:
   workflow_dispatch:
+    inputs:
+      release-version:
+        description: Release version (vX.X)
+        required: true
+        type: string
+      branch-name:
+        description: Branch to release (prepare-release-vX.X)
+        required: true
+        type: string
+      pat-token:
+        description: PAT token (with workflow permissions)
+        required: true
+        type: string
 
 jobs:
-  say-hello:
+  dispatch-release:
     runs-on: ubuntu-latest
+
     steps:
-      - name: Echo message
-        run: echo "Hello"
+      - name: Checkout aggregator repository
+        uses: actions/checkout@v4
+        with:
+          submodules: false
+
+      - name: Mask GH_TOKEN Token
+        run: |
+          echo "::add-mask::$PAT_TOKEN"
+          echo "GH_TOKEN=$PAT_TOKEN" >> $GITHUB_ENV
+        env:
+          PAT_TOKEN: ${{ github.event.inputs.pat-token}} # just for defense against script injection
+
+      - name: Validate pat-token input
+        run: |
+          scopes=$(gh api -i user 2>&1 | grep -i 'x-oauth-scopes:' | cut -d' ' -f2-)
+
+          if [[ -n "$scopes" && "$scopes" == *"workflow"* ]]; then
+              echo "✅ Token is valid and has the 'workflow' scope"
+          elif [[ -n "$scopes" ]]; then
+              echo "⚠️ Token is valid but missing the 'workflow' scope"
+              exit 1
+          else
+              echo "❌ Invalid token"
+              exit 1
+          fi
+
+      - name: Load repo list from file or input
+        id: load_repos
+        run: |
+          if [[ -z "$REPOS_TO_RELEASE" ]]; then
+            echo "ℹ️ No user input → load .github/config/repos-to-release.txt"
+            list="$(cat .github/config/repos-to-release.txt)"
+          else
+            echo "ℹ️ Input found → load user input"
+            list="$REPOS_TO_RELEASE"
+          fi
+          echo "list<<EOF" >> $GITHUB_OUTPUT
+          echo "$list" >> $GITHUB_OUTPUT
+          echo "EOF" >> $GITHUB_OUTPUT
+        env:
+          REPOS_TO_RELEASE: ${{ github.event.inputs.repos_to_release }}
+
+      - name: Create tags and trigger release workflows
+        run: |
+          while read url; do
+
+            version=$RELEASE_VERSION
+            branch_name=origin/$BRANCH_NAME
+
+            owner=$(echo "$url" | cut -d/ -f4)
+            repo=$(echo "$url" | cut -d/ -f5 | sed 's/\.git$//')
+
+            gh api repos/$owner/$repo/actions/workflows/release.yml/dispatches \
+              -f ref=main \
+              -f inputs[releaseVersion]="$version" \
+              -f inputs[gitReference]="$branch_name"
+              
+          done <<< "$REPOS_LIST"
+        env:
+          REPOS_LIST: ${{ steps.load_repos.outputs.list }}
+          RELEASE_VERSION: ${{github.event.inputs.release-version}}
+          BRANCH_NAME: ${{github.event.inputs.branch-name}}
diff --git a/.github/workflows/prepare-release.yml b/.github/workflows/prepare-release.yml
--- a/.github/workflows/prepare-release.yml
+++ b/.github/workflows/prepare-release.yml
@@ -2,10 +2,158 @@ name: Prepare release
 
 on:
   workflow_dispatch:
+    inputs:
+      repos_to_release:
+        description: "Manual list of repositories to release (.github/config/repos-to-release.txt content if left empty)"
+        default: ""
+        required: false
+      target_date:
+        description: "Date of last commit to inlude (ISO 8601, ex: 2024-09-13T23:59:59Z - default : last friday 23:59:59)."
+        required: false
+      release-version:
+        description: "Version for new tag (ex: 2.8.0)"
+        required: true
+    secrets:
+      VERSIONBUMP_GHAPP_PRIVATE_KEY:
+        required: true
 
 jobs:
-  say-hello:
+  prepare-release:
     runs-on: ubuntu-latest
     steps:
-      - name: Echo message
-        run: echo "Hello"
+      - name: Checkout aggregator repository
+        uses: actions/checkout@v4
+        with:
+          submodules: false
+
+      - name: Validate inputs
+        run: |
+          if [ -n "$TARGET_DATE" ]; then
+            if ! date -d "$TARGET_DATE" "+%Y-%m-%dT%H:%M:%SZ" >/dev/null 2>&1; then
+              echo "❌ Invalid date"
+              exit 1
+            fi
+            echo "✅ Valid date"
+          else
+            echo "ℹ️ No date provided, will fallback to last friday"
+          fi
+
+          if [[ "$RELEASE_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "✅ Valid version"
+          else
+            echo "❌ Invalid version"
+            exit 1
+          fi
+
+          if [ -n "$REPOS_TO_RELEASE" ]; then
+            CONFIG_FILE=".github/config/repos-to-release.txt"
+
+            # Convert multi-line input to table
+            IFS=$'\n' read -d '' -r -a urls <<< "$REPOS_TO_RELEASE"
+
+            # Check earch url is contained in config file
+            for url in "${urls[@]}"; do
+              if ! grep -Fxq "$url" "$CONFIG_FILE"; then
+                echo "❌ URL '$url' is unauthorized"
+                exit 1
+              fi
+            done
+          fi
+
+          echo "✅ All URLs are valid"
+        env:
+          REPOS_TO_RELEASE: ${{ github.event.inputs.repos_to_release }} # just for defense against script injection
+          RELEASE_VERSION: ${{ github.event.inputs.release-version }} # just for defense against script injection
+          TARGET_DATE: ${{ github.event.inputs.target_date }} # just for defense against script injection
+
+      - uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1 v1.11.6
+        id: app-token
+        name: Generate app token
+        with:
+          app-id: ${{ vars.GRIDSUITE_ACTIONS_APPID }}
+          private-key: ${{ secrets.VERSIONBUMP_GHAPP_PRIVATE_KEY }}
+          owner: gridsuite
+
+      - name: Get GitHub App User ID
+        id: get-user-id
+        run: | 
+          echo $(gh api "/users/${RUNGHA_APP_SLUG}[bot]")
+          echo "user-id=$(gh api "/users/${RUNGHA_APP_SLUG}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
+        env:
+          GH_TOKEN: ${{ steps.app-token.outputs.token }}
+          RUNGHA_APP_SLUG: ${{ steps.app-token.outputs.app-slug }} # just for defense against script injection
+
+      - name: Setup git user
+        run: |
+          git config --global user.name "${RUNGHA_APP_SLUG}[bot]"
+          git config --global user.email "${RUNGHA_USER_ID}+${RUNGHA_APP_SLUG}[bot]@users.noreply.github.com"
+        env:
+          RUNGHA_APP_SLUG: ${{ steps.app-token.outputs.app-slug }} # just for defense against script injection
+          RUNGHA_USER_ID: ${{ steps.get-user-id.outputs.user-id }} # just for defense against script injection
+
+      - name: Load repo list from file or input
+        id: load_repos
+        run: |
+          if [[ -z "$REPOS_TO_RELEASE" ]]; then
+            echo "ℹ️ No user input → load .github/config/repos-to-release.txt"
+            list="$(cat .github/config/repos-to-release.txt)"
+          else
+            echo "ℹ️ Input found → load user input"
+            list="$REPOS_TO_RELEASE"
+          fi
+          echo "list<<EOF" >> $GITHUB_OUTPUT
+          echo "$list" >> $GITHUB_OUTPUT
+          echo "EOF" >> $GITHUB_OUTPUT
+        env:
+          REPOS_TO_RELEASE: ${{ github.event.inputs.repos_to_release }} # just for defense against script injection
+
+      - name: Extract last commit date (last friday 23:59 UTC if left empty)
+        id: load_date
+        run: |
+          if [ -z "$TARGET_DATE" ]; then
+            date_value=$(date -u -d "last friday 23:59" +"%Y-%m-%dT%H:%M:%SZ")
+          else
+            date_value="$TARGET_DATE"
+          fi
+          echo "date_value=$date_value" >> $GITHUB_OUTPUT
+          echo "This limit date will be used : $date_value"
+        env:
+          TARGET_DATE: ${{ github.event.inputs.target_date }} # just for defense against script injection
+
+      - name: Create "prepare" branches
+        run: |
+          mkdir public_repos
+          cd public_repos
+
+          while read url; do
+              url_with_token="${url/https:\/\/github.com/https:\/\/x-access-token:${TOKEN}@github.com}"
+              git clone "$url_with_token"
+              folder=$(basename "$url" .git)
+              cd $folder
+              commit_date="$COMMIT_DATE"
+              commit_hash=$(git rev-list -n 1 --before="$commit_date" main)
+              git  -c advice.detachedHead=false checkout $commit_hash
+
+              branch_name="prepare-release-v$RELEASE_VERSION"
+              # Check if *branch_name* already exists
+              if git ls-remote --exit-code origin "refs/heads/$branch_name"; then
+                  echo "❌ Warning for $folder: Branch $branch_name already exists"
+                  exit 1
+              fi
+              git checkout -b "$branch_name"
+
+              if ! git push origin "$branch_name"; then
+                  echo "❌ Error for $folder: Failed to push $branch_name"
+                  exit 1
+              fi
+
+              commit_message=$(git log -1 --pretty=%s | cut -c1-50)
+
+              echo "✅ $folder : $branch_name branch created → $commit_hash | $commit_message"
+              cd - > /dev/null
+          done <<< "$REPO_LIST"
+        env:
+          COMMIT_DATE: ${{ steps.load_date.outputs.date_value }} # just for defense against script injection
+          REPO_LIST: ${{ steps.load_repos.outputs.list }} # just for defense against script injection
+          TOKEN: ${{ steps.app-token.outputs.token }} # just for defense against script injection
+          RELEASE_VERSION: ${{github.event.inputs.release-version}} # just for defense against script injection
